package Modelo;
// Generated 12-04-2019 20:19:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private Integer idcliente;
     private Comuna comuna;
     private String nombre;
     private String appaterno;
     private String apmaterno;
     private String direccion;
     private String telefono;
     private String email;
     private String passwd;
     private String rut;
     private Set<Reservas> reservasesForPropietario = new HashSet<Reservas>(0);
     private Set<Propiedades> propiedadeses = new HashSet<Propiedades>(0);
     private Set<Reservas> reservasesForComprador = new HashSet<Reservas>(0);

    public Clientes() {
    }

	
    public Clientes(Integer idcliente, Comuna comuna, String nombre, String appaterno, String apmaterno, String direccion, String telefono, String passwd) {
        this.idcliente = idcliente;
        this.comuna = comuna;
        this.nombre = nombre;
        this.appaterno = appaterno;
        this.apmaterno = apmaterno;
        this.direccion = direccion;
        this.telefono = telefono;
        this.passwd = passwd;
    }
    public Clientes(Integer idcliente, Comuna comuna, String nombre, String appaterno, String apmaterno, String direccion, String telefono, String email, String passwd, String rut, Set<Reservas> reservasesForPropietario, Set<Propiedades> propiedadeses, Set<Reservas> reservasesForComprador) {
       this.idcliente = idcliente;
       this.comuna = comuna;
       this.nombre = nombre;
       this.appaterno = appaterno;
       this.apmaterno = apmaterno;
       this.direccion = direccion;
       this.telefono = telefono;
       this.email = email;
       this.passwd = passwd;
       this.rut = rut;
       this.reservasesForPropietario = reservasesForPropietario;
       this.propiedadeses = propiedadeses;
       this.reservasesForComprador = reservasesForComprador;
    }
   
    public Integer getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(Integer idcliente) {
        this.idcliente = idcliente;
    }
    public Comuna getComuna() {
        return this.comuna;
    }
    
    public void setComuna(Comuna comuna) {
        this.comuna = comuna;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAppaterno() {
        return this.appaterno;
    }
    
    public void setAppaterno(String appaterno) {
        this.appaterno = appaterno;
    }
    public String getApmaterno() {
        return this.apmaterno;
    }
    
    public void setApmaterno(String apmaterno) {
        this.apmaterno = apmaterno;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPasswd() {
        return this.passwd;
    }
    
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }
    public String getRut() {
        return this.rut;
    }
    
    public void setRut(String rut) {
        this.rut = rut;
    }
    public Set<Reservas> getReservasesForPropietario() {
        return this.reservasesForPropietario;
    }
    
    public void setReservasesForPropietario(Set<Reservas> reservasesForPropietario) {
        this.reservasesForPropietario = reservasesForPropietario;
    }
    public Set<Propiedades> getPropiedadeses() {
        return this.propiedadeses;
    }
    
    public void setPropiedadeses(Set<Propiedades> propiedadeses) {
        this.propiedadeses = propiedadeses;
    }
    public Set<Reservas> getReservasesForComprador() {
        return this.reservasesForComprador;
    }
    
    public void setReservasesForComprador(Set<Reservas> reservasesForComprador) {
        this.reservasesForComprador = reservasesForComprador;
    }




}


