package Modelo;
// Generated 12-04-2019 20:19:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Comuna generated by hbm2java
 */
public class Comuna  implements java.io.Serializable {


     private Integer idcomuna;
     private Provincia provincia;
     private String nombrecomuna;
     private Set<Propiedades> propiedadeses = new HashSet<Propiedades>(0);
     private Set<Clientes> clienteses = new HashSet<Clientes>(0);

    public Comuna() {
    }

	
    public Comuna(Integer idcomuna, Provincia provincia, String nombrecomuna) {
        this.idcomuna = idcomuna;
        this.provincia = provincia;
        this.nombrecomuna = nombrecomuna;
    }
    public Comuna(Integer idcomuna, Provincia provincia, String nombrecomuna, Set<Propiedades> propiedadeses, Set<Clientes> clienteses) {
       this.idcomuna = idcomuna;
       this.provincia = provincia;
       this.nombrecomuna = nombrecomuna;
       this.propiedadeses = propiedadeses;
       this.clienteses = clienteses;
    }
   
    public Integer getIdcomuna() {
        return this.idcomuna;
    }
    
    public void setIdcomuna(Integer idcomuna) {
        this.idcomuna = idcomuna;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public String getNombrecomuna() {
        return this.nombrecomuna;
    }
    
    public void setNombrecomuna(String nombrecomuna) {
        this.nombrecomuna = nombrecomuna;
    }
    public Set<Propiedades> getPropiedadeses() {
        return this.propiedadeses;
    }
    
    public void setPropiedadeses(Set<Propiedades> propiedadeses) {
        this.propiedadeses = propiedadeses;
    }
    public Set<Clientes> getClienteses() {
        return this.clienteses;
    }
    
    public void setClienteses(Set<Clientes> clienteses) {
        this.clienteses = clienteses;
    }




}


