package Modelo;
// Generated 12-04-2019 20:19:43 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Estadopropiedad generated by hbm2java
 */
public class Estadopropiedad  implements java.io.Serializable {


     private Integer idestado;
     private String estado;
     private Set<Propiedades> propiedadeses = new HashSet<Propiedades>(0);

    public Estadopropiedad() {
    }

	
    public Estadopropiedad(Integer idestado, String estado) {
        this.idestado = idestado;
        this.estado = estado;
    }
    public Estadopropiedad(Integer idestado, String estado, Set<Propiedades> propiedadeses) {
       this.idestado = idestado;
       this.estado = estado;
       this.propiedadeses = propiedadeses;
    }
   
    public Integer getIdestado() {
        return this.idestado;
    }
    
    public void setIdestado(Integer idestado) {
        this.idestado = idestado;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<Propiedades> getPropiedadeses() {
        return this.propiedadeses;
    }
    
    public void setPropiedadeses(Set<Propiedades> propiedadeses) {
        this.propiedadeses = propiedadeses;
    }




}


