package Modelo;
// Generated 12-04-2019 20:19:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Negocio generated by hbm2java
 */
public class Negocio  implements java.io.Serializable {


     private Integer idnegocio;
     private String negocio;
     private Set<Propiedades> propiedadeses = new HashSet<Propiedades>(0);

    public Negocio() {
    }

	
    public Negocio(Integer idnegocio) {
        this.idnegocio = idnegocio;
    }
    public Negocio(Integer idnegocio, String negocio, Set<Propiedades> propiedadeses) {
       this.idnegocio = idnegocio;
       this.negocio = negocio;
       this.propiedadeses = propiedadeses;
    }
   
    public Integer getIdnegocio() {
        return this.idnegocio;
    }
    
    public void setIdnegocio(Integer idnegocio) {
        this.idnegocio = idnegocio;
    }
    public String getNegocio() {
        return this.negocio;
    }
    
    public void setNegocio(String negocio) {
        this.negocio = negocio;
    }
    public Set<Propiedades> getPropiedadeses() {
        return this.propiedadeses;
    }
    
    public void setPropiedadeses(Set<Propiedades> propiedadeses) {
        this.propiedadeses = propiedadeses;
    }




}


