package Modelo;
// Generated 12-04-2019 20:19:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Propiedades generated by hbm2java
 */
public class Propiedades  implements java.io.Serializable {


     private Integer idpropiedad;
     private Comuna comuna;
     private Tipopropiedad descripcion;
     private Estadopropiedad estado;
     private Negocio negocio;
     private Clientes idcliente;
     private String direccion;
     private String medidas;
     private String detalle;
     private Set<Reservas> reservases = new HashSet<Reservas>(0);

    public Propiedades() {
    }

	
    public Propiedades(Integer idpropiedad, Comuna comuna, Tipopropiedad descripcion, Clientes idcliente, String direccion, String medidas) {
        this.idpropiedad = idpropiedad;
        this.comuna = comuna;
        this.descripcion = descripcion;
        this.idcliente = idcliente;
        this.direccion = direccion;
        this.medidas = medidas;
    }
    public Propiedades(Integer idpropiedad, Comuna comuna, Tipopropiedad descripcion, Estadopropiedad estado, Negocio negocio, Clientes idcliente, String direccion, String medidas, String detalle, Set<Reservas> reservases) {
       this.idpropiedad = idpropiedad;
       this.comuna = comuna;
       this.descripcion = descripcion;
       this.estado = estado;
       this.negocio = negocio;
       this.idcliente = idcliente;
       this.direccion = direccion;
       this.medidas = medidas;
       this.detalle = detalle;
       this.reservases = reservases;
    }
   
    public Integer getIdpropiedad() {
        return this.idpropiedad;
    }
    
    public void setIdpropiedad(Integer idpropiedad) {
        this.idpropiedad = idpropiedad;
    }
    public Comuna getComuna() {
        return this.comuna;
    }
    
    public void setComuna(Comuna comuna) {
        this.comuna = comuna;
    }
    public Tipopropiedad getTipopropiedad() {
        return this.descripcion;
    }
    
    public void setTipopropiedad(Tipopropiedad descripcion) {
        this.descripcion = descripcion;
    }
    public Estadopropiedad getEstadopropiedad() {
        return this.estado;
    }
    
    public void setEstadopropiedad(Estadopropiedad estado) {
        this.estado = estado;
    }
    public Negocio getNegocio() {
        return this.negocio;
    }
    
    public void setNegocio(Negocio negocio) {
        this.negocio = negocio;
    }
    public Clientes getClientes() {
        return this.idcliente;
    }
    
    public void setClientes(Clientes idcliente) {
        this.idcliente = idcliente;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getMedidas() {
        return this.medidas;
    }
    
    public void setMedidas(String medidas) {
        this.medidas = medidas;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public Set<Reservas> getReservases() {
        return this.reservases;
    }
    
    public void setReservases(Set<Reservas> reservases) {
        this.reservases = reservases;
    }




}


