package Modelo;
// Generated 12-04-2019 20:19:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Provincia generated by hbm2java
 */
public class Provincia  implements java.io.Serializable {


     private Integer idprovincia;
     private Region region;
     private String nombreprovincia;
     private Set<Comuna> comunas = new HashSet<Comuna>(0);

    public Provincia() {
    }

	
    public Provincia(Integer idprovincia, Region region, String nombreprovincia) {
        this.idprovincia = idprovincia;
        this.region = region;
        this.nombreprovincia = nombreprovincia;
    }
    public Provincia(Integer idprovincia, Region region, String nombreprovincia, Set<Comuna> comunas) {
       this.idprovincia = idprovincia;
       this.region = region;
       this.nombreprovincia = nombreprovincia;
       this.comunas = comunas;
    }
   
    public Integer getIdprovincia() {
        return this.idprovincia;
    }
    
    public void setIdprovincia(Integer idprovincia) {
        this.idprovincia = idprovincia;
    }
    public Region getRegion() {
        return this.region;
    }
    
    public void setRegion(Region region) {
        this.region = region;
    }
    public String getNombreprovincia() {
        return this.nombreprovincia;
    }
    
    public void setNombreprovincia(String nombreprovincia) {
        this.nombreprovincia = nombreprovincia;
    }
    public Set<Comuna> getComunas() {
        return this.comunas;
    }
    
    public void setComunas(Set<Comuna> comunas) {
        this.comunas = comunas;
    }




}


