package Modelo;
// Generated 12-04-2019 20:19:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Region generated by hbm2java
 */
public class Region  implements java.io.Serializable {


     private Integer idregion;
     private String nombreregion;
     private String ordinalreg;
     private Set<Provincia> provincias = new HashSet<Provincia>(0);

    public Region() {
    }

	
    public Region(Integer idregion, String nombreregion) {
        this.idregion = idregion;
        this.nombreregion = nombreregion;
    }
    public Region(Integer idregion, String nombreregion, String ordinalreg, Set<Provincia> provincias) {
       this.idregion = idregion;
       this.nombreregion = nombreregion;
       this.ordinalreg = ordinalreg;
       this.provincias = provincias;
    }
   
    public Integer getIdregion() {
        return this.idregion;
    }
    
    public void setIdregion(Integer idregion) {
        this.idregion = idregion;
    }
    public String getNombreregion() {
        return this.nombreregion;
    }
    
    public void setNombreregion(String nombreregion) {
        this.nombreregion = nombreregion;
    }
    public String getOrdinalreg() {
        return this.ordinalreg;
    }
    
    public void setOrdinalreg(String ordinalreg) {
        this.ordinalreg = ordinalreg;
    }
    public Set<Provincia> getProvincias() {
        return this.provincias;
    }
    
    public void setProvincias(Set<Provincia> provincias) {
        this.provincias = provincias;
    }




}


