package Modelo;
// Generated 12-04-2019 20:19:43 by Hibernate Tools 4.3.1


import java.io.Serializable;
/**
 * Reservas generated by hbm2java
 */
public class Reservas  implements java.io.Serializable {


     private Integer idreserva;
     private Propiedades propiedades;
     private Clientes clientesByPropietario;
     private Clientes clientesByComprador;
     private Serializable inicioreserva;
     private Serializable finreserva;
     private Integer montoreservauf;
     private Integer estadoreserva;

    public Reservas() {
    }

    public Reservas(Integer idreserva, Propiedades propiedades, Clientes clientesByPropietario, Clientes clientesByComprador, Serializable inicioreserva, Serializable finreserva, Integer montoreservauf, Integer estadoreserva) {
       this.idreserva = idreserva;
       this.propiedades = propiedades;
       this.clientesByPropietario = clientesByPropietario;
       this.clientesByComprador = clientesByComprador;
       this.inicioreserva = inicioreserva;
       this.finreserva = finreserva;
       this.montoreservauf = montoreservauf;
       this.estadoreserva = estadoreserva;
    }
   
    public Integer getIdreserva() {
        return this.idreserva;
    }
    
    public void setIdreserva(Integer idreserva) {
        this.idreserva = idreserva;
    }
    public Propiedades getPropiedades() {
        return this.propiedades;
    }
    
    public void setPropiedades(Propiedades propiedades) {
        this.propiedades = propiedades;
    }
    public Clientes getClientesByPropietario() {
        return this.clientesByPropietario;
    }
    
    public void setClientesByPropietario(Clientes clientesByPropietario) {
        this.clientesByPropietario = clientesByPropietario;
    }
    public Clientes getClientesByComprador() {
        return this.clientesByComprador;
    }
    
    public void setClientesByComprador(Clientes clientesByComprador) {
        this.clientesByComprador = clientesByComprador;
    }
    public Serializable getInicioreserva() {
        return this.inicioreserva;
    }
    
    public void setInicioreserva(Serializable inicioreserva) {
        this.inicioreserva = inicioreserva;
    }
    public Serializable getFinreserva() {
        return this.finreserva;
    }
    
    public void setFinreserva(Serializable finreserva) {
        this.finreserva = finreserva;
    }
    public Integer getMontoreservauf() {
        return this.montoreservauf;
    }
    
    public void setMontoreservauf(Integer montoreservauf) {
        this.montoreservauf = montoreservauf;
    }
    public Integer getEstadoreserva() {
        return this.estadoreserva;
    }
    
    public void setEstadoreserva(Integer estadoreserva) {
        this.estadoreserva = estadoreserva;
    }




}


