package Modelo;
// Generated 12-04-2019 20:19:43 by Hibernate Tools 4.3.1



/**
 * Ventas generated by hbm2java
 */
public class Ventas  implements java.io.Serializable {


     private Integer idventa;
     private Integer idpropietario;
     private Integer idcomprador;
     private Integer valorpropiedad;
     private Integer segdegravamen;
     private Integer segincendio;
     private String costooperacion;
     private Integer conservador;

    public Ventas() {
    }

	
    public Ventas(Integer idventa) {
        this.idventa = idventa;
    }
    public Ventas(Integer idventa, Integer idpropietario, Integer idcomprador, Integer valorpropiedad, Integer segdegravamen, Integer segincendio, String costooperacion, Integer conservador) {
       this.idventa = idventa;
       this.idpropietario = idpropietario;
       this.idcomprador = idcomprador;
       this.valorpropiedad = valorpropiedad;
       this.segdegravamen = segdegravamen;
       this.segincendio = segincendio;
       this.costooperacion = costooperacion;
       this.conservador = conservador;
    }
   
    public Integer getIdventa() {
        return this.idventa;
    }
    
    public void setIdventa(Integer idventa) {
        this.idventa = idventa;
    }
    public Integer getIdpropietario() {
        return this.idpropietario;
    }
    
    public void setIdpropietario(Integer idpropietario) {
        this.idpropietario = idpropietario;
    }
    public Integer getIdcomprador() {
        return this.idcomprador;
    }
    
    public void setIdcomprador(Integer idcomprador) {
        this.idcomprador = idcomprador;
    }
    public Integer getValorpropiedad() {
        return this.valorpropiedad;
    }
    
    public void setValorpropiedad(Integer valorpropiedad) {
        this.valorpropiedad = valorpropiedad;
    }
    public Integer getSegdegravamen() {
        return this.segdegravamen;
    }
    
    public void setSegdegravamen(Integer segdegravamen) {
        this.segdegravamen = segdegravamen;
    }
    public Integer getSegincendio() {
        return this.segincendio;
    }
    
    public void setSegincendio(Integer segincendio) {
        this.segincendio = segincendio;
    }
    public String getCostooperacion() {
        return this.costooperacion;
    }
    
    public void setCostooperacion(String costooperacion) {
        this.costooperacion = costooperacion;
    }
    public Integer getConservador() {
        return this.conservador;
    }
    
    public void setConservador(Integer conservador) {
        this.conservador = conservador;
    }




}


